apriltag:
  ros__parameters:
    family: tag36h11
    id: [500, 501]
    tx: [1.0, -1.0]
    ty: [1.0, -1.0]
    tz: [1.0, -1.0]
    qw: [0.0, 1.0]
    qx: [1.0, 0.0]
    qy: [0.0, 0.0]
    qz: [0.0, 0.0]
